import {
  Heading1,
  Heading2,
  Heading3,
  AlignLeft,
  List,
  ListOrdered,
  Quote,
  Minus,
  Image as ImageIcon,
  Youtube,
  Video,
  FileVideo,
  AudioLines,
  Images,
  Code,
  Download,
  ExternalLink,
  FileText,
  Target,
  BookOpen,
  Lightbulb,
  AlertTriangle,
  Dumbbell,
  Trophy,
  HelpCircle,
  type LucideIcon,
} from "lucide-react";

export const typeIconMap: Record<string, LucideIcon> = {
  h1: Heading1,
  h2: Heading2,
  h3: Heading3,
  paragraph: AlignLeft,
  text: AlignLeft,
  bullet_list: List,
  list: List,
  numbered_list: ListOrdered,
  quote: Quote,
  divider: Minus,
  image: ImageIcon,
  youtube: Youtube,
  vimeo: Video,
  video_file: FileVideo,
  audio: AudioLines,
  gallery: Images,
  code: Code,
  download_button: Download,
  external_link: ExternalLink,
  pdf_embed: FileText,
  objectives: Target,
  summary: BookOpen,
  tip: Lightbulb,
  warning: AlertTriangle,
  exercise: Dumbbell,
  challenge: Trophy,
  open_question: HelpCircle,
};

export const typeLabelMap: Record<string, string> = {
  h1: "Título H1",
  h2: "Título H2",
  h3: "Título H3",
  paragraph: "Párrafo",
  bullet_list: "Lista con viñetas",
  numbered_list: "Lista numerada",
  quote: "Cita",
  divider: "Separador",
  image: "Imagen",
  youtube: "Vídeo YouTube",
  vimeo: "Vídeo Vimeo",
  video_file: "Archivo de vídeo",
  audio: "Audio",
  gallery: "Galería",
  code: "Bloque de código",
  download_button: "Botón descarga",
  external_link: "Enlace externo",
  pdf_embed: "PDF incrustado",
  objectives: "Objetivos de aprendizaje",
  summary: "Resumen",
  tip: "Consejo",
  warning: "Advertencia",
  exercise: "Ejercicio",
  challenge: "Reto",
  open_question: "Pregunta abierta",
};
